### ISSUE TITLE
MNIST experiments available ?

### ISSUE THREAD

**Issue by aymeric75** [alper111/affordance-learning#4]
Hello,

Thanks for your work. I would like to know if the MNIST experiment is available (i.e. dataset etc), I could not find it on the repo

Cheers

Aymeric

**Comment by alper111** [comment]
Hi Aymeric,

They are not available on this repo, yet, as they are somewhat messy. Though I can add you to the private repo where you can find MNIST8Tile gym-like environment.

Edit: I realized that it is a public repo, but it's still a little bit drafty: https://github.com/alper111/deepsym-scratch

**Comment by alper111** [comment]
Scripts starting with `exp3_` contains relevant experiments for the MNIST 8-Tile environment. Please let me know if something is missing, or not very clear.
